name: Laravel

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Laravel project
      run: composer create-project laravel/laravel easypaisa
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install dependencies
      run: composer install
      
    - name: Generate key
      run:  php artisan key:generate
