name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Laravel project
        run: composer create-project laravel/laravel easypaisa

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install
        
      - name: Dump autoload
        run: composer dump-autoload

      - name: Set appropriate permissions
        run: chmod -R 777 storage
        
      - name: Require Easypaisa package
        run: composer require zfhassaan/easypaisa
        
      - name: Publish Easypaisa package resources
        run: php artisan vendor:publish --provider="zfhassaan\Easypaisa\EasyPaisaServiceProvider" 

      - name: Dump autoload
        run: composer dump-autoload
        
      - name: Run EasypaisaDirectController test
        run: php artisan test --filter=EasypaisaDirectTest

      - name: Run EasypaisaHostedController test
        run: php artisan test --filter=EasypaisaHostedTest
