name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Laravel project
        run: composer create-project laravel/laravel easypaisa

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install
        
      - name: Require laravel
        run:  composer require laravel/laravel
        
      - name: Dump autoload
        run: composer dump-autoload
        
      - name: make directory storage
        run:  mkdir storage

      - name: make bootstrap
        run:  mkdir bootstrap/cache

      - name: Set appropriate permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Require Easypaisa package
        run: composer require zfhassaan/easypaisa
