name: Laravel Project Easypaisa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Laravel project
        run: composer create-project laravel/laravel easypaisa
        
      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Generate application key
        run: php artisan key:generate

      - name: Set appropriate permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Require Easypaisa package
        run: composer require zfhassaan/easypaisa

      - name: Publish Easypaisa package resources
        run: php artisan vendor:publish

      - name: Dump autoload
        run: composer dump-autoload

      - name: Run EasypaisaDirectController test
        run: php artisan test --filter=EasypaisaDirectTest

      - name: Run EasypaisaHostedController test
        run: php artisan test --filter=EasypaisaHostedTest
