name: Laravel

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
